#Atividade Prática 2 - Grupo 6

Participantes: Antonio Henrique, Pedro Lucca, Samuel Santos e Naum Celestino

### Introdução

Este trabalho tem como objetivo a análise textual das contratações emergenciais dos munícipios e Estado do Piauí, realizadas no período de março a setembro de 2020, referentes ao enfrentamento da pandemia da COVID-19. Os dados foram extraídos dos respectivos diários oficiais por uma comissão do Tribunal de Contas do Estado do Piauí, criada especificamente para o acompanhamento dessas contratações, e inseridos em uma planilha Excel. Desta forma, o corpus do trabalho foi construído baseado a partir da coluna “Objeto” da planilha em questão, e assim, será analisado o uso das palavras no corpus, extraindo as principais features que nos ajudam a entender o contexto e saber qual tratamento podemos fazer com o texto.




Tipos de representações de features são medidas estatísticas que servem para indicar a importância de um determinado termo em um documento ou um conjunto de documentos. No tipo de representação binária define-se uma feature para cada palavra, que vai informar se o documento possui ou não essa palavra.

Em Term-Frequency o peso de um termo é diretamente proporcional a sua fequencia em um documento. Nele cada documento é representado por um vetor que contêm a quantidade de cada termo.

A principal diferença entre Term-frequency(TF) e term frequency inverse document frequency(TF-IDF) é que enquanto TF faz uma analise da frequência das palavras em cada texto, o TF-IDF adiciona a equação o inverso da frequência dessas palavras no Corpus. A idéia é alterar o peso dos termos nos documentos de forma a impedir que termos que sejam muito frequentes em varios documentos diferentes tenham pesos semelhantes a termos que são frequentes em um documento, mas raros no Corpus. 


### Resultados


In [ ]:
#Para a leitura do arquivo da segunda atividade
import io
import pandas as pd
import nltk
from sklearn.feature_extraction.text import CountVectorizer

git_doc = 'https://github.com/PedroLucca/PLN-exercises/blob/master/diarios_oficiais_COVID_classific.xlsx?raw=true'
dfs = pd.read_excel(git_doc, sheet_name=None)
dfs['diarios_oficiais'].head(5)


Esfera  ... Natureza_de_Despesa
0  Estadual  ...       Não informado
1  Estadual  ...       Não informado
2  Estadual  ...       Não informado
3  Estadual  ...       Não informado
4  Estadual  ...       Não informado

[5 rows x 22 columns]

In [ ]:
diarios = dfs['diarios_oficiais']
#corpus = pd.DataFrame(diarios, columns= ['Objeto'])
#obj = corpus.head(5).to_numpy()
corpus = diarios.get('Objeto').to_numpy().tolist()
print(corpus[-5:])
corpus_obj_simp = diarios.get('Objeto_simplificado').to_numpy().tolist()

['Contratação de Empresa para fornecimentos de Teste Rápido para detecção especifica de IGG e IGM do COVID-19, para o Município de Dom Inocêncio - PI.', 'Prestação de contrataçao de profissional para dar suporte técnico ao desenvolvimento do trabalho de: Acompanhamento a Lei Emergenclal Cultural Aldir Biano, sancionada através do Decreto Federal no 14.017/2020; Alimentação dos sistemas e plataformas necessárias; acompanhamento e julgamento dos editais, todo suporte técnico ao Setor de Cultura junto a Secretaria Municipal de Cultura, Esporte e Lazer e a Prefeitura Municipal de São Jose do Piaul - PI.', 'AQUISIÇÃO DE PULVERIZADOR 20 LT FIBRA BICO PLASTICO PARA SECRETARIA MUNICIPAL DE EDUCAÇÃO E ESCOLAS DA REDE ESTADUAL E MUNICIPAL DO MUNICÍPIO DE SÃO JOSÉ DO PIAUÍ· PI.', 'AQUISIÇÃO DE ÁGUA SANITÁRIA I LT, DETERGENTE 500 ML E PAPEL TOALHA PARA SECRETARIA MUNICIPAL DE EDUCAÇÃO E SEUS RESPECTNOS ÓRGÃOS DO MUNICtPIO DE SÃO JOSE DO PIAUÍ - PI.', 'PRESTAÇÃO DE SERVIÇOS DE TROCA DE PISO DA SECR

In [ ]:
from nltk.corpus import stopwords
nltk.download('stopwords')
sw = stopwords.words('portuguese')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
#Importar nltk
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
#Tokenizar dados e remover stopwords

new_sw = (['atender', 'novo', 'contrato', 'saúde', 'coronavírus', 'combate', 'secretaria', 'objeto',
           'covid', 'pública', '2020', 'municipal', 'pi','necessidades', '00', '19',
           'pandemia', 'ações', 'coronavirus', 'município', 'municipio', 'termo', 'emergencial', 'piauí',
           'emergência', 'nº', 'interesse', 'presente', 'decorrente', 'fornecimento', 'valor', 'conforme',
           'aditivo', 'caráter', 'destinados', 'medidas', 'atendimento', 'prevenção', 'necessidade',
           'excepcional', 'lei', 'pacientes', 'enfrentamento'])
sw.extend(new_sw)
#sw.append(['secretaria', 'municipal', 'pi', 'saúde', 'covid']) 
#'prestação', 'contratação', 'aquisição', 'serviços' 

def tokenizar(corpus):
  tokens = []
  for objeto in corpus:
      tokens_objeto = nltk.word_tokenize(objeto, language='portuguese')
      tokens_objeto = [token.lower() for token in tokens_objeto]
      for token in tokens_objeto:
          tokens.append(token)
  tokens_menos_sw = []
  for t in tokens:
    if t not in sw and t.isalpha() :
      tokens_menos_sw.append(t)
  return tokens_menos_sw

In [ ]:
dados_obj = tokenizar(corpus)
dados_obj_simpl = tokenizar(corpus_obj_simp)

dados_totais = dados_obj + dados_obj_simpl

print(len(dados_obj))

77595


In [ ]:
#Binário
import random

#Pegando as palavras mais frequentes
allWords = nltk.FreqDist(w.lower() for w in dados_obj)


#key_words = list(allWords)[0:20]
key_words = ('teste', 'testes', 'rápidos', 'igg', 'igm', 'alimentação', 'reforma', 'medicamentos', 
             'especializada', 'locação', 'serviço', 'serviços', 'cargo', 'epi', 'epis', 'epi\'s', 
             'máscara' 'máscaras', 'materiais', 'empresa', 'luvas', 'leitos', 'limpeza', 'higiene', 
             'hospitalar', 'enfermeiro', 'médico', 'álcool', 'gel', 'insumos', 'veículos', 'equipamentos', 
             'física', 'pessoa', 'temporário', 'função')

def corpus_features(doc):
  i = 1
# doc_words = [w for w in dados_obj]
  doc_words = key_words
  feats = {}
  #if i == 1:
    #print(doc_words)
    #i = i + 1
  for word in doc_words:
    if (word in doc):
      feats[f'countains({word})'] = True
#      feats[f'countains({word})'] = (word in doc)
  return feats

labeled_names = []
for i in range(len(corpus)):
#    print(i, corpus[i], corpus_obj_simp[i])
    labeled_names.append([corpus[i], corpus_obj_simp[i]])  

#labeled_names = ([(name, 'obj') for name in dados_obj[0:5000]] + [(name, 'obj_simpl') for name in dados_obj_simpl[0:5000]])
print(labeled_names[-5:])
random.shuffle(labeled_names)

featuresets = [(corpus_features(n), cat) for (n, cat) in labeled_names]
train_set, test_set = featuresets[0:5400], featuresets[5400:]
classifier = nltk.NaiveBayesClassifier.train(train_set)
print("Taxa de acurácia da classificação: ",nltk.classify.accuracy(classifier, test_set))
print(classifier.show_most_informative_features())

[['Contratação de Empresa para fornecimentos de Teste Rápido para detecção especifica de IGG e IGM do COVID-19, para o Município de Dom Inocêncio - PI.', 'Aquisição de testes para diagnóstico de COVID-19'], ['Prestação de contrataçao de profissional para dar suporte técnico ao desenvolvimento do trabalho de: Acompanhamento a Lei Emergenclal Cultural Aldir Biano, sancionada através do Decreto Federal no 14.017/2020; Alimentação dos sistemas e plataformas necessárias; acompanhamento e julgamento dos editais, todo suporte técnico ao Setor de Cultura junto a Secretaria Municipal de Cultura, Esporte e Lazer e a Prefeitura Municipal de São Jose do Piaul - PI.', 'Contratação de prestador de serviço - pessoa física'], ['AQUISIÇÃO DE PULVERIZADOR 20 LT FIBRA BICO PLASTICO PARA SECRETARIA MUNICIPAL DE EDUCAÇÃO E ESCOLAS DA REDE ESTADUAL E MUNICIPAL DO MUNICÍPIO DE SÃO JOSÉ DO PIAUÍ· PI.', 'Aquisição de equipamentos diversos'], ['AQUISIÇÃO DE ÁGUA SANITÁRIA I LT, DETERGENTE 500 ML E PAPEL TOALHA 

In [ ]:
#Formato TF


# Cria o objeto vetorizador
vectorizer = CountVectorizer(analyzer='word', binary=False, decode_error='strict', encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=20, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=sw,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)


# Aplica o vetorizador nos dados
vectorizer.fit(corpus)


# Saída:

print("Temos um dicionário com o termo e suas respectivas frequências, ou seja quantas vezes aquele termo apareceu na base de dados:\n",vectorizer.vocabulary_)

# Aplicando o transformador
matrix = vectorizer.transform(corpus)

# Visualizando a forma da matriz gerada
print("\nSHAPE:",matrix.shape)

# Imprimindo a matriz binária
print("\n",matrix.toarray())

#esse vetor tem muitos zeros, por essa razão eles são chamados de vetores esparsos.

Temos um dicionário com o termo e suas respectivas frequências, ou seja quantas vezes aquele termo apareceu na base de dados:
 {'empresa': 1, 'prestação': 13, 'serviço': 17, 'aquisição': 0, 'equipamentos': 3, 'médico': 12, 'material': 10, 'hospitalar': 7, 'hospital': 6, 'especializada': 4, 'materiais': 9, 'serviços': 18, 'profissionais': 14, 'medicamentos': 11, 'público': 16, 'proteção': 15, 'individual': 8, 'horas': 5, 'enfermagem': 2, 'social': 19}

SHAPE: (6190, 20)

 [[0 1 0 ... 1 0 0]
 [1 1 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]]


In [ ]:
#Formato Tf-idf
from sklearn.feature_extraction.text import TfidfVectorizer


# Instanciar o objeto TFIDF 
vectorizer = TfidfVectorizer(analyzer='word', binary=False, decode_error='strict', encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=20,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=sw, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)


# Constroi o vetorizador nos dados
vectorizer.fit(corpus)

# saída:

# Imprime o vocabulario
print(vectorizer.vocabulary_)

print("\n","Essas são as pontuações que foram dadas para cada um dos termos da base de dados. As palavras mais relevantes tem uma pontuação maior:\n",vectorizer.idf_)

# Aplicando aos dados
matrix = vectorizer.transform(corpus)

# Imprime a forma da matrix
print("\n","SHAPE:",matrix.shape)
print("\n",matrix.toarray())

{'empresa': 1, 'prestação': 13, 'serviço': 17, 'aquisição': 0, 'equipamentos': 3, 'médico': 12, 'material': 10, 'hospitalar': 7, 'hospital': 6, 'especializada': 4, 'materiais': 9, 'serviços': 18, 'profissionais': 14, 'medicamentos': 11, 'público': 16, 'proteção': 15, 'individual': 8, 'horas': 5, 'enfermagem': 2, 'social': 19}

 Essas são as pontuações que foram dadas para cada um dos termos da base de dados. As palavras mais relevantes tem uma pontuação maior:
 [2.20845167 2.86287749 3.97195013 3.78543129 3.96253091 4.21339901
 3.51624381 4.05752864 4.18177582 3.91374074 3.57387292 3.82821857
 4.21339901 2.5919849  3.76470516 3.64180703 4.19351764 3.68584659
 2.26806275 4.03711976]

 SHAPE: (6190, 20)

 [[0.         0.53626686 0.         ... 0.69042331 0.         0.        ]
 [0.32864902 0.42603689 0.         ... 0.         0.         0.        ]
 [0.32864902 0.42603689 0.         ... 0.         0.         0.        ]
 ...
 [1.         0.         0.         ... 0.         0.         0.

### Conclusão


Foi criado o corpus a partir da célula "Objeto" da planilha dos diários oficiais referenciada no início do trabalho. Desse corpus, retiramos as stopwords da lígua porteguesa. Retiramos também, as palavras que entendíamos não ter relevância na classificação dos objetos.

Na representação de features binárias, escolhemos um conjunto de palavras, que consideramos serem relevantes na classificação dos objetos para as classes de "objetos simplificados", e criamos uma feature se havia ou não a palavra no documento. Nessa representação, criamos um modelo experimental utilizando o método Navie Bayes como classificador. Separamos a base treinamento e base de teste e colocamos nosso modelo para executar algumas vezes. Na última versão, a acurácia variava de 0,45 a 0,5025, sendo que nas versões iniciais desse modelo a acurácia estava por volta de 0,35. 

Por fim, implementamos as representações TF e TF-IDF. Inicicialmente, nos dois casos, configuramos o número de features muito grande (500), o que fazia com o que nossa matriz só desse para visualizar 0s. Com a diminuição desse parâmetro para 20, conseguimos visualizar o funcionamento do método, identificando as palavras que continham nos documentos, tanto na frequência das palavras no TF, quanto no cálculo do TF-IDF.